# Generated by Django 5.1.6 on 2025-02-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_wines_delete_perfil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="coins",
            field=models.IntegerField(default=5000),
        ),
    ]
