# Generated by Django 5.1.6 on 2025-02-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wines", "0004_category_remove_wine_pairing_wine_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wine",
            name="acidity",
            field=models.IntegerField(
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                default=2,
            ),
        ),
        migrations.AlterField(
            model_name="wine",
            name="aging",
            field=models.IntegerField(
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                default=2,
            ),
        ),
        migrations.AlterField(
            model_name="wine",
            name="aroma",
            field=models.IntegerField(
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                default=2,
            ),
        ),
        migrations.AlterField(
            model_name="wine",
            name="body",
            field=models.IntegerField(
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                default=2,
            ),
        ),
        migrations.AlterField(
            model_name="wine",
            name="image",
            field=models.ImageField(default="wines/img.jpg", upload_to="wines/"),
        ),
        migrations.AlterField(
            model_name="wine",
            name="sweetness",
            field=models.IntegerField(
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                default=2,
            ),
        ),
        migrations.AlterField(
            model_name="wine",
            name="tannins",
            field=models.IntegerField(
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                default=2,
            ),
        ),
        migrations.AlterField(
            model_name="wine",
            name="taste",
            field=models.IntegerField(
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                default=2,
            ),
        ),
    ]
